- name: Check folder
  ansible.builtin.debug:
    msg: "name={{ repo.name }} path={{ repo.path }}"

- name: stat folder {{ repo.path }}
  stat:
    path: "{{ repo.path }}"
  register: folder_info
  delegate_to: localhost
  
- name: Print some info
  ansible.builtin.debug:
    msg: "{{ folder_info.stat.exists }}"

- name: If folder not exist fail exit
  ansible.builtin.fail:
    msg: "Folder {{ repo.path }} not exist"
  when: folder_info.stat.exists == False