---
- name: Fetch the project data from GitLab API
  uri:
    url: "{{ GITLAB_URL }}/api/v4/projects?search={{ project_name }}"
    headers:
      PRIVATE-TOKEN: "{{ NEW_USER_TOKEN }}"
    return_content: yes
  register: temp_result

- name: Check if project data contains projects
  fail:
    msg: "No project found with the name '{{ project_name }}'"
  when: (temp_result.content | from_json) | length == 0

- name: Extract the project ID
  set_fact:
    "{{ result_var_name }}": "{{ (temp_result.content | from_json)[0].id }}"
  when: (temp_result.content | from_json) | length > 0

- name: Display the Project ID
  debug:
    msg: "Found Project {{ project_name }} with ID: {{ result_var_name }}"
  when: (temp_result.content | from_json) | length == 0

