---


- name: Fetch the project data from GitLab API
  uri:
    url: "{{ GITLAB_URL }}/api/v4/projects?search={{ project_name }}&simple=true"
    headers:
      PRIVATE-TOKEN: "{{ NEW_USER_TOKEN }}"
    return_content: yes
  retries: 10
  delay: 5
  register: get_project_id_result

- name: Check if project data contains projects
  fail:
    msg: "No project found with the name '{{ project_name }}'"
  when: (get_project_id_result.content | from_json) | length == 0

- block:
  - name: Extract the project ID
    set_fact:
      "{{ result_var_name }}": "{{ project_item.id }}"
    when: project_item.name == project_name
    with_items: "{{ get_project_id_result.json }}"
    loop_control:
      loop_var: project_item
      label: "{{ project_item.name }}"
  when: not (get_project_id_result.content | from_json) | length == 0

