- name: Get GitLab container IP
  command: docker inspect -f "{{ '{{' }} .NetworkSettings.Networks.bridge.IPAddress {{ '}}' }}" gitlab-server
  register: gitlab_ip_result
  changed_when: false

- name: Print GitLab container IP
  ansible.builtin.debug:
    msg: "{{ gitlab_ip_result.stdout }}"