---
driver:
  name: docker
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
  # Add the role-name to skip_list or warn_list as shown below:
  ansible-galaxy-import --skip-list role-name
platforms:
  - name: docker-host
    hostname: docker-host
    image: "docker-python3:24.0.2-dind"
    privileged: true        
    # platform: "linux/amd64"  
    platform: "linux/arm64"  
    # network: networkmolecule
    # ipaddress: "172.16.100.101"
scenario:
  name: default
  create_sequence:
    - dependency
    - create
    - prepare
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
    
provisioner:
  name: ansible
  collections:
    - path: ./molecule/default/requirements.yml
  playbooks:
    converge: converge.yml
  inventory:
    group_vars:
      all:
        repo_directory_list: 
          - { name: "frontend", branch: "master", path: "../../../../frontend" }
          - { name: "frontend-build", branch: "main", path: "../../../../frontend_build" }


verifier:
  name: ansible

